steps:
  - name: build-image
    image: docker
    commands:
      - docker build --rm -t local/project-image .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      - branch: main
        event: push

  - name: build
    image: local/project-image
    environment:
      RECC_SERVER: 192.168.1.111:8980
      RECC_CAS_SERVER: 192.168.1.111:8980
      RECC_ACTION_CACHE_SERVER: 192.168.1.111:8980
      RECC_INSTANCE: fuse
      RECC_LINK: 1
      RECC_REMOTE_PLATFORM_OSFamily: linux
      RECC_REMOTE_PLATFORM_arch: x86_64
    commands:
      - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MAKE_PROGRAM=ninja -G Ninja -S . -B cmake-build-debug
      - cd cmake-build-debug
      - ninja -j8
    when:
      - branch: main
        event: push

  - name: UnitTest
    image: local/project-image
    commands:
      -  ./cmake-build-debug/test/UnitTests/UnitTests
    when:
      - branch: main
        event: push
